### PR TITLE
Merge in master changes covering KNIME 4 fixes

### PR DESCRIPTION
**Pull request by webbres**
The KNIME 4.1 CDK build is currently failing due to the resolved issue w.r.t the testing feature dependency. 

This pull request coverings merging in the license updates and testing dependency changes made to master. 

This should then resolve the failing build for version 4.1

### CODE REVIEW

**Comment by webbres** [comment]
https://forum.knime.com/t/4-1-knime-community-build-issues/23142

It would appear that we actually want to create a new release branch for 4.1 which contains the master changes. 

@egonw Could you please create a new branch releases/4.1 (from master?) and I'll update the jenkins job?

Edit: it's already been merged so releases/4.1 could also branch from releases/4.0 :). Running the 4.1 build now to confirm the merge fixed the issue

**Comment by webbres** [comment]
The merge fixed the build 👍

**Comment by egonw** [comment]
I created the https://github.com/cdk/nodes4knime/tree/releases/4.1 branch.

I also noted there were still two old jars. So, please check if the latest `master` commits also needs to be applied to the new `release/4.1` branch.

PS, thx for your work! I've not had a lot of time recently to do much on this, except to help out with small maintenance updates via PRs that come in :) Maybe @ammar257ammar will be able to help out in the future.

**Comment by webbres** [comment]
Thank you :) 

Yes it would make sense to merge that change into 4.1

**Pull request merged**
